version: "3.8"

services:
  postgres:
    image: postgres:15-alpine # Lightweight PostgreSQL
    environment:
      POSTGRES_USER: postgres # Default username
      POSTGRES_PASSWORD: postgres # Default password
      POSTGRES_DB: mvpdb # Default DB name
    ports:
      - "5432:5432" # Expose PostgreSQL to host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data: # Named volume for data persistence
